"""
Patch v1_9: back-fill the Fixed Asset accounts (Fixed Assets - Cost,
Accumulated Depreciation, Capital Work in Progress, Depreciation Expense)
for every EXISTING company.

Background:
    _seed_coa()'s COA list now includes a "Fixed Assets" group plus leaf
    accounts typed "Fixed Asset" / "Accumulated Depreciation" / "Depreciation",
    so any NEW company created after this patch gets them automatically via
    bootstrap_company_data(). Companies that already existed before this
    change (e.g. VK Herbal formulations) never ran that seeding step for
    these rows — which meant the Asset Category "Accounting" section had
    nothing to offer in its Fixed Asset / Accumulated Depreciation /
    Depreciation Expense pickers. This patch runs the same idempotent
    insert logic against every company already in the system.

Non-destructive and idempotent: only inserts accounts that don't already
exist (checked by full account name "{account_name} - {company}"); never
renames or deletes anything. Safe to re-run.
"""
import frappe

from zoho_books_clone.books_setup.install import _all_company_names

# (account_name, account_type, parent_name)
FIXED_ASSET_ACCOUNTS = [
    ("Fixed Assets",             "Asset",                   None),                # group
    ("Fixed Assets - Cost",      "Fixed Asset",              "Fixed Assets"),
    ("Accumulated Depreciation", "Accumulated Depreciation", "Fixed Assets"),
    ("Capital Work in Progress", "Asset",                   "Fixed Assets"),
    ("Depreciation Expense",     "Depreciation",             "Operating Expenses"),
]


def _find_account(company, account_name, is_group=None):
    """Look up an account by its logical (company, account_name[, is_group])
    identity instead of guessing the auto-named document name. Account.name
    is auto-generated by Frappe core from the company's *abbreviation*
    (e.g. "Assets - PSD"), which can drift out of sync with the company's
    display name after a rename — so string-building "{name} - {company}"
    is not reliable and must not be used for lookups.
    """
    filters = {"company": company, "account_name": account_name}
    if is_group is not None:
        filters["is_group"] = is_group
    return frappe.db.get_value("Account", filters, "name")


def execute():
    if not frappe.db.exists("DocType", "Account"):
        return

    for company in _all_company_names():
        assets_parent = _find_account(company, "Assets", is_group=1)
        opex_parent = _find_account(company, "Operating Expenses", is_group=1)

        # Track accounts created earlier in this same loop iteration (e.g.
        # "Fixed Assets" group) so later rows in FIXED_ASSET_ACCOUNTS can
        # resolve it as a parent without a stale re-query assumption.
        created_this_run = {}

        for name, atype, parent in FIXED_ASSET_ACCOUNTS:
            existing = _find_account(company, name)
            if existing:
                continue

            if name == "Fixed Assets":
                parent_full = assets_parent
                is_group = 1
            elif parent == "Operating Expenses":
                parent_full = opex_parent
                is_group = 0
            else:
                parent_full = created_this_run.get(parent) or _find_account(company, parent)
                is_group = 0

            # Guard against a missing parent (e.g. a company whose base COA
            # never seeded "Assets" or "Operating Expenses" for some reason)
            # rather than inserting an orphaned account.
            if not parent_full:
                frappe.log_error(
                    title="Patch v1_9",
                    message=(
                        f"v1_9: skipping fixed-asset account seed for "
                        f"'{company}/{name}' — parent account "
                        f"'{parent or 'Assets'}' not found for this company."
                    ),
                )
                continue

            try:
                doc = frappe.get_doc({
                    "doctype": "Account",
                    "account_name": name,
                    "account_type": atype,
                    "parent_account": parent_full,
                    "is_group": is_group,
                    "company": company,
                    "currency": "INR",
                }).insert(ignore_permissions=True)
                created_this_run[name] = doc.name
            except Exception as exc:
                frappe.log_error(
                    title="Patch v1_9",
                    message=f"v1_9: fixed-asset account seed — {company}/{name}: {exc}",
                )

    frappe.db.commit()
    print("✅  v1_9: Fixed Asset accounts back-filled for all companies.")