"""
Test — Manufacturing Stock Entry Row Identity (QC coverage angle)
===================================================================
Companion to quality/test_qc_row_identity.py, scoped to the manufacturing
side of the same bug class.

work_order_engine.complete_work_order / issue_materials build a Stock Entry
and call se.insert() then se.submit() in the same Python call, on the same
in-memory doc -- never through api/docs.py::save_doc's JSON round-trip.
That structural difference is WHY these were never vulnerable to the
row-identity bug that hit Purchase Invoice via Bills.vue's two-step
save-then-submit through the SPA. This suite pins that structural
invariant down so it can't silently regress (e.g. someone "simplifying"
complete_work_order to save a draft first and submit separately later).

It does not re-test get_or_create_coverage's own logic (see
test_qc_coverage_safeguard.py) -- only that the manufacturing call sites
feed it row objects whose .name is already stable at the point
auto_create_qc_for_stock_entry runs.

Run with:
    bench --site <site> run-tests --module zoho_books_clone.manufacturing.tests.test_qc_row_identity_manufacturing
"""
from __future__ import annotations

import ast
import inspect
import unittest

import frappe


class TestManufacturingStockEntryIsInsertedThenSubmittedAtomically(unittest.TestCase):
    """
    Static-shape check on work_order_engine.py: for each Stock-Entry-
    producing function, `se.insert(...)` must be immediately followed by
    `se.submit()` on the SAME `se` object, with no intervening save_doc /
    api call / re-fetch that could hand the row a new identity in between.
    """

    @classmethod
    def setUpClass(cls):
        from zoho_books_clone.manufacturing import work_order_engine
        cls.source = inspect.getsource(work_order_engine)
        cls.tree = ast.parse(cls.source)

    def _calls_in_function(self, func_name):
        for node in ast.walk(self.tree):
            if isinstance(node, ast.FunctionDef) and node.name == func_name:
                calls = []
                for n in ast.walk(node):
                    if isinstance(n, ast.Call) and isinstance(n.func, ast.Attribute):
                        calls.append(n.func.attr)
                return calls
        self.fail(f"Function {func_name} not found in work_order_engine.py")

    def test_complete_work_order_inserts_then_submits_same_object(self):
        calls = self._calls_in_function("complete_work_order")
        self.assertIn("insert", calls)
        self.assertIn("submit", calls)
        self.assertLess(
            calls.index("insert"), calls.index("submit"),
            "complete_work_order must insert() the Stock Entry before submit()",
        )
        # No save_doc / api client round-trip anywhere in this function --
        # that round-trip is exactly what stripped row names for Purchase
        # Invoice.
        self.assertNotIn("save_doc", calls)

    def test_issue_materials_inserts_then_submits_same_object(self):
        calls = self._calls_in_function("issue_materials")
        self.assertIn("insert", calls)
        self.assertIn("submit", calls)
        self.assertLess(calls.index("insert"), calls.index("submit"))
        self.assertNotIn("save_doc", calls)


class TestQCHookFiresOnceOnFirstSubmit(unittest.TestCase):
    """
    Behavioural check with a fake Stock Entry-like object: simulates what
    auto_create_qc_for_stock_entry sees when called from a doc that was
    insert()-then-submit()-ed in one call, i.e. every row already has a
    stable .name before the hook ever runs -- so get_or_create_coverage
    only ever needs to take the "create" branch once per row, never the
    "row identity drifted, create again" path.
    """

    def test_row_name_is_assigned_before_before_submit_hook_runs(self):
        # Mirrors Frappe's real sequencing: insert() assigns child row
        # names; only afterwards does submit() run before_submit hooks.
        class _FakeRow:
            def __init__(self, item_code):
                self.item_code = item_code
                self.name = None

        class _FakeStockEntry:
            def __init__(self):
                self.items = [_FakeRow("FG-ITEM-001")]
                self._name_counter = 0

            def insert(self, ignore_permissions=True):
                self._name_counter += 1
                for row in self.items:
                    row.name = f"se-row-{self._name_counter}"

            def submit(self):
                # before_submit hooks would run here, against self.items,
                # whose .name values were already fixed by insert() above
                # and are never regenerated by this call.
                for row in self.items:
                    assert row.name, "row must already have a stable name at submit time"

        se = _FakeStockEntry()
        se.insert()
        name_after_insert = se.items[0].name
        se.submit()
        self.assertEqual(se.items[0].name, name_after_insert)


if __name__ == "__main__":
    unittest.main()